[jsnsr04t.broadcast.udp]
    enabled = true
    address = "239.255.255.255"
    port = 3378

[jsnsr04t.broadcast.bluetooth]
    enabled = true
    mode = "server"
    channel = 16

[jsnsr04t]
    trigger = 12
    echo = 11